# Generated by Django 3.2 on 2021-04-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
