# Generated by Django 3.2 on 2021-04-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20210415_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='fullname',
            field=models.CharField(default='<Django.Db.Models.Fields.Charfield> <Django.Db.Models.Fields.Charfield>', max_length=130),
        ),
    ]
