# Generated by Django 3.2 on 2021-04-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_player_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='fullname',
            field=models.CharField(blank=True, max_length=130),
        ),
    ]
