# Generated by Django 3.2 on 2021-04-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='jersey_number',
            field=models.PositiveSmallIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='jersey_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
